### ISSUE TITLE
Arq Backup Cache

### ISSUE THREAD

**Issue by notDavid** [SterlingHooten/borg-backup-exclusions-macos#3]
Hi there, please consider adding the folder `/Library/Application Support/ArqAgent/cache.noindex` - a cache folder of the [Arq](https://www.arqbackup.com/) app.

I think it might be a good idea to add just the subfolder name `cache.noindex`, since i think Arq can also be run as a regular user (not root/admin), in which case i assume the cache will be in something like "~/Library..."

Also, thanks for the repo/lists :-)

**Comment by SterlingHooten** [comment]
Thanks for the addition!
Added ! **/Library/Application Support/ArqAgent/cache.noindex which should cover the condition that it's run a regular user.
Let me know if it pops up again.
